from __future__ import annotations

MUNICIPIOS_POR_DEPARTAMENTO: dict[str, list[str]] = {
    "GUATEMALA": [
        "GUATEMALA", "SANTA CATARINA PINULA", "SAN JOSE PINULA", "SAN JOSE DEL GOLFO",
        "PALENCIA", "CHINAUTLA", "SAN PEDRO AYAMPUC", "MIXCO", "SAN PEDRO SACATEPEQUEZ",
        "SAN JUAN SACATEPEQUEZ", "SAN RAYMUNDO", "CHUARRANCHO", "FRAIJANES", "AMATITLAN",
        "VILLA NUEVA", "VILLA CANALES", "SAN MIGUEL PETAPA",
    ],
    "EL PROGRESO": [
        "GUASTATOYA", "MORAZAN", "SAN AGUSTIN ACASAGUASTLAN", "SAN CRISTOBAL ACASAGUASTLAN",
        "EL JICARO", "SANSARE", "SANARATE", "SAN ANTONIO LA PAZ",
    ],
    "SACATEPEQUEZ": [
        "ANTIGUA GUATEMALA", "JOCOTENANGO", "PASTORES", "SUMPANGO", "SANTO DOMINGO XENACOJ",
        "SANTIAGO SACATEPEQUEZ", "SAN BARTOLOME MILPAS ALTAS", "SAN LUCAS SACATEPEQUEZ",
        "SANTA LUCIA MILPAS ALTAS", "MAGDALENA MILPAS ALTAS", "SANTA MARIA DE JESUS",
        "CIUDAD VIEJA", "SAN MIGUEL DUEÑAS", "ALOTENANGO", "SAN ANTONIO AGUAS CALIENTES",
        "SANTA CATARINA BARAHONA",
    ],
    "CHIMALTENANGO": [
        "CHIMALTENANGO", "SAN JOSE POAQUIL", "SAN MARTIN JILOTEPEQUE", "SAN JUAN COMALAPA",
        "SANTA APOLONIA", "TECPAN GUATEMALA", "PATZUN", "POCHUTA", "PATZICIA",
        "SANTA CRUZ BALANYA", "ACATENANGO", "YEPOCAPA", "SAN ANDRES ITZAPA", "PARRAMOS",
        "ZARAGOZA", "EL TEJAR",
    ],
    "ESCUINTLA": [
        "ESCUINTLA", "SANTA LUCIA COTZUMALGUAPA", "LA DEMOCRACIA", "SIQUINALA", "MASAGUA",
        "TIQUISATE", "LA GOMERA", "GUANAGAZAPA", "SAN JOSE", "IZTAPA", "PALIN",
        "SAN VICENTE PACAYA", "NUEVA CONCEPCION",
    ],
    "SANTA ROSA": [
        "CUILAPA", "BARBERENA", "SANTA ROSA DE LIMA", "CASILLAS", "SAN RAFAEL LAS FLORES",
        "ORATORIO", "SAN JUAN TECUACO", "CHIQUIMULILLA", "TAXISCO", "SANTA MARIA IXHUATAN",
        "GUAZACAPAN", "SANTA CRUZ NARANJO", "PUEBLO NUEVO VIÑAS", "NUEVA SANTA ROSA",
    ],
    "SOLOLA": [
        "SOLOLA", "SAN JOSE CHACAYA", "SANTA MARIA VISITACION", "SANTA LUCIA UTATLAN",
        "NAHUALA", "SANTA CATARINA IXTAHUACAN", "SANTA CLARA LA LAGUNA", "CONCEPCION",
        "SAN ANDRES SEMETABAJ", "PANAJACHEL", "SANTA CATARINA PALOPO", "SAN ANTONIO PALOPO",
        "SAN LUCAS TOLIMAN", "SANTA CRUZ LA LAGUNA", "SAN PABLO LA LAGUNA",
        "SAN MARCOS LA LAGUNA", "SAN JUAN LA LAGUNA", "SAN PEDRO LA LAGUNA",
        "SANTIAGO ATITLAN",
    ],
    "TOTONICAPAN": [
        "TOTONICAPAN", "SAN CRISTOBAL TOTONICAPAN", "SAN FRANCISCO EL ALTO",
        "SAN ANDRES XECUL", "MOMOSTENANGO", "SANTA MARIA CHIQUIMULA", "SANTA LUCIA LA REFORMA",
        "SAN BARTOLO",
    ],
    "QUETZALTENANGO": [
        "QUETZALTENANGO", "SALCAJA", "OLINTEPEQUE", "SAN CARLOS SIJA", "SIBILIA", "CABRICAN",
        "CAJOLA", "SAN MIGUEL SIGUILA", "SAN JUAN OSTUNCALCO", "SAN MATEO",
        "CONCEPCION CHIQUIRICHAPA", "SAN MARTIN SACATEPEQUEZ", "ALMOLONGA", "CANTEL",
        "HUITAN", "ZUNIL", "COLOMBA", "SAN FRANCISCO LA UNION", "EL PALMAR", "COATEPEQUE",
        "GENOVA", "FLORES COSTA CUCA", "LA ESPERANZA", "PALESTINA DE LOS ALTOS",
    ],
    "SUCHITEPEQUEZ": [
        "MAZATENANGO", "CUYOTENANGO", "SAN FRANCISCO ZAPOTITLAN", "SAN BERNARDINO",
        "SAN JOSE EL IDOLO", "SANTO DOMINGO SUCHITEPEQUEZ", "SAN LORENZO", "SAMAYAC",
        "SAN PABLO JOCOPILAS", "SAN ANTONIO SUCHITEPEQUEZ", "SAN MIGUEL PANAN",
        "SAN GABRIEL", "CHICACAO", "PATULUL", "SANTA BARBARA", "SAN JUAN BAUTISTA",
        "SANTO TOMAS LA UNION", "ZUNILITO", "PUEBLO NUEVO SUCHITEPEQUEZ", "RIO BRAVO",
        "SAN JOSE LA MAQUINA",
    ],
    "RETALHULEU": [
        "RETALHULEU", "SAN SEBASTIAN", "SANTA CRUZ MULUA", "SAN MARTIN ZAPOTITLAN",
        "SAN FELIPE", "SAN ANDRES VILLA SECA", "CHAMPERICO", "NUEVO SAN CARLOS",
        "EL ASINTAL",
    ],
    "SAN MARCOS": [
        "SAN MARCOS", "SAN PEDRO SACATEPEQUEZ", "SAN ANTONIO SACATEPEQUEZ", "COMITANCILLO",
        "SAN MIGUEL IXTAHUACAN", "CONCEPCION TUTUAPA", "TACANA", "SIBINAL", "TAJUMULCO",
        "TEJUTLA", "SAN RAFAEL PIE DE LA CUESTA", "NUEVO PROGRESO", "EL TUMBADOR",
        "EL RODEO", "MALACATAN", "CATARINA", "AYUTLA", "OCOS", "SAN PABLO", "EL QUETZAL",
        "LA REFORMA", "PAJAPITA", "IXCHIGUAN", "SAN JOSE OJETENAM", "SAN CRISTOBAL CUCHO",
        "SIPACAPA", "ESQUIPULAS PALO GORDO", "RIO BLANCO", "SAN LORENZO", "LA BLANCA",
    ],
    "HUEHUETENANGO": [
        "HUEHUETENANGO", "CHIANTLA", "MALACATANCITO", "CUILCO", "NENTON", "SAN PEDRO NECTA",
        "JACALTENANGO", "SAN PEDRO SOLOMA", "SAN ILDEFONSO IXTAHUACAN",
        "TODOS SANTOS CUCHUMATAN", "SAN JUAN ATITAN", "SANTA EULALIA", "SAN MATEO IXTATAN",
        "COLOTENANGO", "SAN SEBASTIAN HUEHUETENANGO", "TECTITAN", "CONCEPCION HUISTA",
        "SAN JUAN IXCOY", "SAN ANTONIO HUISTA", "SAN SEBASTIAN COATAN",
        "SANTA CRUZ BARILLAS", "AGUACATAN", "SAN RAFAEL LA INDEPENDENCIA",
        "LA DEMOCRACIA", "SAN MIGUEL ACATAN", "SAN RAFAEL PETZAL", "SAN GASPAR IXCHIL",
        "SANTIAGO CHIMALTENANGO", "SANTA ANA HUISTA", "UNION CANTINIL",
    ],
    "QUICHE": [
        "SANTA CRUZ DEL QUICHE", "CHICHE", "CHINIQUE", "ZACUALPA", "CHAJUL",
        "CHICHICASTENANGO", "PATZITE", "SAN ANTONIO ILOTENANGO", "SAN PEDRO JOCOPILAS",
        "CUNEN", "SAN JUAN COTZAL", "JOYABAJ", "NEBAJ", "SAN ANDRES SAJCABAJA", "USPANTAN",
        "SACAPULAS", "SAN BARTOLOME JOCOTENANGO", "CANILLA", "CHICAMAN", "IXCAN",
        "PACHALUM",
    ],
    "BAJA VERAPAZ": [
        "SALAMA", "SAN MIGUEL CHICAJ", "RABINAL", "CUBULCO", "GRANADOS", "EL CHOL",
        "SAN JERONIMO", "PURULHA",
    ],
    "ALTA VERAPAZ": [
        "COBAN", "SANTA CRUZ VERAPAZ", "SAN CRISTOBAL VERAPAZ", "TACTIC", "TAMAHU",
        "TUCURU", "PANZOS", "SENAHU", "SAN PEDRO CARCHA", "SAN JUAN CHAMELCO", "LANQUIN",
        "SANTA MARIA CAHABON", "CHISEC", "CHAHAL", "FRAY BARTOLOME DE LAS CASAS",
        "SANTA CATALINA LA TINTA", "RAXRUHA",
    ],
    "PETEN": [
        "FLORES", "SAN JOSE", "SAN BENITO", "SAN ANDRES", "LA LIBERTAD", "SAN FRANCISCO",
        "SANTA ANA", "DOLORES", "SAN LUIS", "SAYAXCHE", "MELCHOR DE MENCOS", "POPTUN",
        "LAS CRUCES", "EL CHAL",
    ],
    "IZABAL": [
        "PUERTO BARRIOS", "LIVINGSTON", "EL ESTOR", "MORALES", "LOS AMATES",
    ],
    "ZACAPA": [
        "ZACAPA", "ESTANZUELA", "RIO HONDO", "GUALAN", "TECULUTAN", "USUMATLAN",
        "CABAÑAS", "SAN DIEGO", "LA UNION", "HUITE", "SAN JORGE",
    ],
    "CHIQUIMULA": [
        "CHIQUIMULA", "SAN JOSE LA ARADA", "SAN JUAN ERMITA", "JOCOTAN", "CAMOTAN",
        "OLOPA", "ESQUIPULAS", "CONCEPCION LAS MINAS", "QUEZALTEPEQUE", "SAN JACINTO",
        "IPALA",
    ],
    "JALAPA": [
        "JALAPA", "SAN PEDRO PINULA", "SAN LUIS JILOTEPEQUE", "SAN MANUEL CHAPARRON",
        "SAN CARLOS ALZATATE", "MONJAS", "MATAQUESCUINTLA",
    ],
    "JUTIAPA": [
        "JUTIAPA", "EL PROGRESO", "SANTA CATARINA MITA", "AGUA BLANCA", "ASUNCION MITA",
        "YUPILTEPEQUE", "ATESCATEMPA", "JEREZ", "EL ADELANTO", "ZAPOTITLAN", "COMAPA",
        "JALPATAGUA", "CONGUACO", "MOYUTA", "PASACO", "SAN JOSE ACATEMPA", "QUESADA",
    ],
}

DEPARTAMENTOS_OFICIALES = sorted(MUNICIPIOS_POR_DEPARTAMENTO.keys())

_TODOS_LOS_MUNICIPIOS = {
    (depto, mun)
    for depto, municipios in MUNICIPIOS_POR_DEPARTAMENTO.items()
    for mun in municipios
}


def es_departamento_valido(nombre: str) -> bool:
    if not isinstance(nombre, str):
        return False
    return nombre.strip().upper() in DEPARTAMENTOS_OFICIALES


def es_municipio_valido(nombre_municipio: str, nombre_departamento: str) -> bool:
    if not isinstance(nombre_municipio, str) or not isinstance(nombre_departamento, str):
        return False
    return (nombre_departamento.strip().upper(), nombre_municipio.strip().upper()) in _TODOS_LOS_MUNICIPIOS
